--
-- Created by IntelliJ IDEA.
-- User: jordan
-- Date: 3/25/20
-- Time: 5:14 AM
-- To change this template use File | Settings | File Templates.
--

-- NOTE: EVERY OPERATION USES +
-- USE A NEGATIVE VALUE FOR A PENALTY

-- EMPIRE STABILITY MULTIPLIERS
HAPPINESS_MODIFIER =        1
SOCIAL_POLICY_MODIFIER =    1
POLICY_BRANCH_MODIFIER =    1
WONDER_MODIFIER =           2
GOLDEN_AGE_BONUS =          5
WAR_PER_CIV_MODIFIER =     -1
GPT_LOSS_MODIFIER =      -0.2

-- CITY STABILITY MULTIPLIERS
STARVATION_MODIFIER =      -5
GARRISON_BONUS =            1
RELIGION_MODIFIER =      -0.1
REL_MAJORITY_MODIFIER =     3
PUPPET_PENALTY =           -1

-- THRESHOLDS FOR CONDITIONS
GOLD_THRESHOLD =            2

-- CITIES LOST
TURNS_TO_TRACK =            8
CITIES_LOST_MODIFIER =     -5

-- REVOLT MODIFIERS
CITY_REVOLT_MODIFIER =      2

-- At 22, not counting garrison