--
-- Created by IntelliJ IDEA.
-- User: jordan
-- Date: 3/25/20
-- Time: 5:14 AM
-- To change this template use File | Settings | File Templates.
--

-- NOTE: EVERY OPERATION USES +
-- USE A NEGATIVE VALUE FOR A PENALTY

-- EMPIRE STABILITY MULTIPLIERS
HAPPINESS_MODIFIER =        1
SOCIAL_POLICY_MODIFIER =    1
POLICY_BRANCH_MODIFIER =    1
WONDER_MODIFIER =           2
GOLDEN_AGE_BONUS =          5
WAR_PER_CIV_MODIFIER =     -1
GPT_LOSS_MODIFIER =      -0.2

-- CITY STABILITY MULTIPLIERS
STARVATION_PENALTY =       -10
GARRISON_BONUS =            1

-- THRESHOLDS FOR CONDITIONS
GOLD_THRESHOLD =            2